import React from "react";
import ReactDOM from "react-dom/client";
import App from "./app/App";

// IMPORTANT: import the *output* generated by the CLI
import "./tailwind.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
