spring.application.name=myPokerSpring
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,metrics
management.datadog.metrics.export.api-key=${DD_API_KEY:}
management.datadog.metrics.export.uri=https://api.us3.datadoghq.com
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.enabled=${DD_METRICS_ENABLED:false}
management.metrics.tags.application=abhi-poker
management.metrics.tags.env=${DD_ENV:local}